name:PrintBranchName
on:
  push:
    branches:
      - 'main'
jobs:
  print_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch Name
        run: echo "Branch Name: $github.ref"
        